services:
  composer:
    restart: 'no'
    image: composer/composer
    command: install
    volumes:
      - .:/app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - laravel

  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'hugo'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: