version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - MediCarePro:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'hugo'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  MediCarePro: