version: '3.8'

services:
  app:
    image: 'php:7.4-fpm-alpine'
    volumes:
      - .:/var/www/html
      - laravel_vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'hugo'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  laravel_vendor:
